using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Vantage.PMS.Data;
using Vantage.PMS.Models.SystemAdministration;

namespace Vantage.PMS.Pages.System.DocumentTemplateSettings;

public class IndexModel(ApplicationDbContext context) : PageModel
{
    public IList<DocumentTemplateSetting> Settings { get; private set; } = new List<DocumentTemplateSetting>();

    [BindProperty]
    public DocumentTemplateInput Input { get; set; } = new();

    public async Task OnGetAsync()
    {
        await EnsureDefaultsAsync();
        Settings = await context.DocumentTemplateSettings
            .AsNoTracking()
            .OrderBy(setting => setting.DocumentType)
            .ToListAsync();
    }

    public async Task<IActionResult> OnPostSaveAsync()
    {
        if (!ModelState.IsValid)
        {
            Settings = await context.DocumentTemplateSettings.AsNoTracking().OrderBy(setting => setting.DocumentType).ToListAsync();
            return Page();
        }

        var setting = Input.Id > 0
            ? await context.DocumentTemplateSettings.FirstOrDefaultAsync(item => item.Id == Input.Id)
            : null;

        if (setting is null)
        {
            setting = new DocumentTemplateSetting
            {
                CreatedAt = DateTime.Now
            };
            context.DocumentTemplateSettings.Add(setting);
        }

        setting.TemplateName = Input.TemplateName.Trim();
        setting.DocumentType = Input.DocumentType.Trim();
        setting.HeaderTitle = Input.HeaderTitle.Trim();
        setting.FooterText = Input.FooterText;
        setting.ShowLogo = Input.ShowLogo;
        setting.ShowPreparedBy = Input.ShowPreparedBy;
        setting.ShowApprovedBy = Input.ShowApprovedBy;
        setting.ShowPrintedDate = Input.ShowPrintedDate;
        setting.IsActive = Input.IsActive;
        setting.Notes = Input.Notes;
        setting.UpdatedAt = DateTime.Now;

        await context.SaveChangesAsync();
        TempData["StatusMessage"] = "Document template setting saved.";
        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostEditAsync(int id)
    {
        await EnsureDefaultsAsync();
        var setting = await context.DocumentTemplateSettings.AsNoTracking().FirstOrDefaultAsync(item => item.Id == id);
        if (setting is not null)
        {
            Input = new DocumentTemplateInput
            {
                Id = setting.Id,
                TemplateName = setting.TemplateName,
                DocumentType = setting.DocumentType,
                HeaderTitle = setting.HeaderTitle,
                FooterText = setting.FooterText,
                ShowLogo = setting.ShowLogo,
                ShowPreparedBy = setting.ShowPreparedBy,
                ShowApprovedBy = setting.ShowApprovedBy,
                ShowPrintedDate = setting.ShowPrintedDate,
                IsActive = setting.IsActive,
                Notes = setting.Notes
            };
        }

        Settings = await context.DocumentTemplateSettings.AsNoTracking().OrderBy(item => item.DocumentType).ToListAsync();
        return Page();
    }

    private async Task EnsureDefaultsAsync()
    {
        if (await context.DocumentTemplateSettings.AnyAsync())
        {
            return;
        }

        foreach (var documentType in DefaultDocumentTypes)
        {
            context.DocumentTemplateSettings.Add(new DocumentTemplateSetting
            {
                TemplateName = documentType,
                DocumentType = documentType,
                HeaderTitle = documentType,
                FooterText = "Generated by Vantage PMS. Validate official templates before production use.",
                ShowLogo = true,
                ShowPreparedBy = true,
                ShowApprovedBy = true,
                ShowPrintedDate = true,
                IsActive = true,
                Notes = "Default document template setting."
            });
        }

        await context.SaveChangesAsync();
    }

    private static readonly string[] DefaultDocumentTypes =
    [
        "Reservation Confirmation",
        "Registration Card",
        "Guest Folio",
        "Finance Document",
        "Statement of Account",
        "Payment Receipt",
        "Banquet Event Order",
        "Banquet Quotation",
        "POS Bill",
        "Room Charge Slip",
        "Kitchen Order Ticket",
        "Purchase Request",
        "Purchase Order",
        "Receiving Report",
        "Stock Adjustment",
        "Sales Account Profile",
        "Management AI Summary",
        "Client Review Package"
    ];
}

public class DocumentTemplateInput
{
    public int Id { get; set; }

    public string TemplateName { get; set; } = string.Empty;

    public string DocumentType { get; set; } = string.Empty;

    public string HeaderTitle { get; set; } = string.Empty;

    public string? FooterText { get; set; }

    public bool ShowLogo { get; set; } = true;

    public bool ShowPreparedBy { get; set; } = true;

    public bool ShowApprovedBy { get; set; } = true;

    public bool ShowPrintedDate { get; set; } = true;

    public bool IsActive { get; set; } = true;

    public string? Notes { get; set; }
}
