using Microsoft.EntityFrameworkCore;
using Vantage.PMS.Models.Reports;
using Vantage.PMS.Services;

namespace Vantage.PMS.Data;

public static class ReportSeedData
{
    public static async Task SeedAsync(ApplicationDbContext context)
    {
        await SeedTemplateSettingsAsync(context);
        await SeedCatalogItemsAsync(context);
    }

    private static async Task SeedTemplateSettingsAsync(ApplicationDbContext context)
    {
        var defaults = new[]
        {
            new ReportTemplateSetting
            {
                ReportKey = "default",
                ReportName = "Default Vantage Report",
                ReportCategory = ReportCategory.Other,
                HeaderTitle = "Vantage PMS Report",
                FooterText = "Generated by Vantage PMS.",
                DisclaimerText = "Reports are configurable and should be reviewed by authorized personnel before operational or official use.",
                IsActive = true
            },
            new ReportTemplateSetting
            {
                ReportKey = "philippine-finance",
                ReportName = "Philippine Finance Reports",
                ReportCategory = ReportCategory.PhilippineFinance,
                HeaderTitle = "Philippine Finance Report",
                FooterText = "Generated by Vantage PMS.",
                DisclaimerText = "Internal tax-support report only. This is not a certified filing output or real BIR submission tool; validate treatment and formats with a Philippine CPA/accountant before official use.",
                IsActive = true
            },
            new ReportTemplateSetting
            {
                ReportKey = "usali",
                ReportName = "USALI-style Reports",
                ReportCategory = ReportCategory.USALI,
                HeaderTitle = "USALI-style Management Report",
                FooterText = "Generated by Vantage PMS.",
                DisclaimerText = "USALI-style management report. Configure mappings and validate with the hotel accountant before production use.",
                IsActive = true
            },
            new ReportTemplateSetting
            {
                ReportKey = "management-ai",
                ReportName = "Management AI Reports",
                ReportCategory = ReportCategory.ManagementAI,
                HeaderTitle = "Management AI Report",
                FooterText = "Generated by Vantage PMS.",
                DisclaimerText = "Rule-based recommendations only. External AI integration is disabled.",
                IsActive = true
            },
            new ReportTemplateSetting
            {
                ReportKey = "demo",
                ReportName = "Demo Reports",
                ReportCategory = ReportCategory.Demo,
                HeaderTitle = "Demo Report",
                FooterText = "Generated by Vantage PMS.",
                DisclaimerText = "Sample data is for presentation and trial validation only.",
                IsActive = true
            }
        };

        foreach (var setting in defaults)
        {
            if (!await context.ReportTemplateSettings.AnyAsync(existing => existing.ReportKey == setting.ReportKey))
            {
                context.ReportTemplateSettings.Add(setting);
            }
        }
    }

    private static async Task SeedCatalogItemsAsync(ApplicationDbContext context)
    {
        var existingKeys = await context.ReportCatalogItems
            .Select(item => item.ReportKey)
            .ToListAsync();
        var existing = existingKeys.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var sort = 10;

        foreach (var entry in ReportCatalogService.DefaultCatalog)
        {
            if (existing.Contains(entry.ReportKey))
            {
                continue;
            }

            context.ReportCatalogItems.Add(new ReportCatalogItem
            {
                ReportKey = entry.ReportKey,
                ReportName = entry.ReportName,
                ReportCategory = entry.ReportCategory,
                Description = entry.Description,
                RoutePath = entry.RoutePath,
                RequiredRoles = entry.RequiredRolesText,
                SupportsPrint = entry.SupportsPrint,
                SupportsCsvExport = entry.SupportsCsvExport,
                SupportsHtmlExport = entry.SupportsHtmlExport,
                SupportsPdfViaBrowserPrint = entry.SupportsPdfViaBrowserPrint,
                SortOrder = sort,
                IsActive = true
            });
            sort += 10;
        }
    }
}
